name: contracts-cicd

on: [push]

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Compile
        run: $(npm bin hardhat)/hardhat compile
      - name: Test
        run: $(npm bin hardhat)/hardhat test